#!/usr/bin/env bash
#HAproxyyiy
apt-get update
apt-get install haproxy -y

echo "
frontend eyes
    bind *:80
    default_backend heart

backend heart
    balance roundrobin
    server 320277-web-01 52.87.152.249:80 check
    server 320277-web-02 18.235.249.248:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
