#!/bin/bash

# Function to handle SIGTERM signal
terminate() {
    echo "I am invincible!!!"
    exit 0
}

# Trap SIGTERM signal and call the terminate function
trap 'terminate' SIGTERM

# Function to display the message
display_message() {
    while true; do
        echo "To infinity and beyond"
        sleep 2
    done
}

# Call the display_message function in the background
display_message &

# Save the PID of the 7-highlander process
highlander_pid=$!

# Wait for the 7-highlander process to finish or receive a SIGTERM signal
wait $highlander_pid
